#!/usr/bin/env bash

TOP_DIR=$(dirname "${0}")
SCRIPT_NAME=$(basename "${0}")
NBB=${TOP_DIR}/node_modules/.bin/nbb

die() { echo >&2 "${*}"; exit 1; }

[ -e "${NBB}" ] || die "Missing ${NBB}. Maybe run 'npm install' in ${TOP_DIR}?"

exec ${NBB} -cp "${TOP_DIR}/src":"${TOP_DIR}/node_modules/@viasat/cljs-utils/src" "${TOP_DIR}"/${SCRIPT_NAME}.cljs "${@}"
